### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by NicolasUmiastowski** [jncraton/box-line-text#6]
Hello ,

I love this non-UI whiteboard. Actually, it is easier to use than some UI boards, and it is cleaner and nicer!
I felt like the ability to drag and drop the created elements (in order to move them on a another position on the board) would be a nice feature.
What do you think?

**Comment by jncraton** [comment]
Thanks! I'm glad that you've enjoyed using this!

I definitely think that drag and drop would be nice to have.

How would you envision this working? I'm not currently using right click for anything. I am considering using it for [panning](https://github.com/jncraton/box-line-text/pull/2) or some form of drag and drop everything.

**Comment by NicolasUmiastowski** [comment]
It was more to drag an drop one element. Could be the right click or a combination of left-click + some key.
Regarding panning I generally prefer natural scroll.

**Comment by jncraton** [comment]
That makes sense. Hopefully I'll have a chance to explore this at some point.

**Comment by NicolasUmiastowski** [comment]
Have you ever considered the possibility to have a custom menu on right-click of the mouse (instead of the OS menu)? 
Would allow to add more possibilities, without needing to add UI elements: put in bold, italic, add background color, perhaps drag and drop....

**Comment by jncraton** [comment]
I have considered it, and I'm not sure what I'd like to do. I don't like overriding the user agent context menu, especially given that it already provides some useful functionality in Firefox via the "Take Screenshot" option. Right now, I'm leaning towards a help/first time use menu and modifier keys for different advanced actions.

**Comment by jncraton** [comment]
It should now be possible to drag boxes and text around in the development branch:

https://develop--box-line-text.netlify.app/

**Comment by NicolasUmiastowski** [comment]
great I will use this branch
