### ISSUE TITLE
Adjust  box height to text content

### ISSUE THREAD

**Issue by NicolasUmiastowski** [jncraton/box-line-text#7]
After creating a box, when typing a text inside that box, it could be nice if the height of the box adapts to the height of the text.
Use case : I don't know in advance how much long the text will be, so the initial size of the box is arbitrary.

**Comment by jncraton** [comment]
That certainly feels like it could be an improvement over the current behavior. How does the following implementation feel to you?

https://autogrow--box-line-text.netlify.app/

**Comment by NicolasUmiastowski** [comment]
that's it!
I was wondering if it could be the same for width, but of course you have to make a choice between fixed height or fixed width!
There is always the case when a long word makes the text exceed the width of the box... but here.... don't know what could be the best solution to that!

**Comment by jncraton** [comment]
Great! That's a good point about long words. I've pushed another change to expand the width to fit the longest word and still grow the height to fit the full height of the text.

**Comment by NicolasUmiastowski** [comment]
Awesome!
