### ISSUE TITLE
Add line-break at Enter key press in Box?

### ISSUE THREAD

**Issue by NicolasUmiastowski** [jncraton/box-line-text#8]
When writing text inside a box, i wanted to create a list of items, and tried to hit Enter to start a new line. I saw that it does not add a line-break.
Thought it could be nice to have that.

**Comment by jncraton** [comment]
That would be nice. It used to be possible, but I took it out because newlines are handled differently in different browsers. Hopefully I'll have a chance to add this functionality back in a way that can be consistently serialized and deserialized across browsers.

**Comment by NicolasUmiastowski** [comment]
after some thought, I wondered if it's absolutely necessary : could be one idea/topic per box (as in virtual post-it tools)...so we can do without it.

**Comment by jncraton** [comment]
I agree that it isn't absolutely necessary. However, I also think that this is something that most users (and my own muscle memory) expect to just work, so I'd like to add it if I can figure out a clean way to do it.

**Comment by jncraton** [comment]
I've worked this feature back into the [persistence branch](https://persistence--box-line-text.netlify.app/#1GCDDList$1.+First+%F0%9F%98%80$2.+Second).

**Comment by NicolasUmiastowski** [comment]
works great on chrome. Will use it.
